/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class image_ConvolutionEngine */

#ifndef _Included_image_ConvolutionEngine
#define _Included_image_ConvolutionEngine
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     image_ConvolutionEngine
 * Method:    convolveNative
 * Signature: ([III[FI)[I
 */
JNIEXPORT jintArray JNICALL Java_image_ConvolutionEngine_convolveNative
  (JNIEnv *, jobject, jintArray, jint, jint, jfloatArray, jint);

#ifdef __cplusplus
}
#endif
#endif
